services:
  experiments-postgres:
    image: postgres:latest
    container_name: experiments_postgres
    restart: always
    environment:
      POSTGRES_USER: experiments
      POSTGRES_PASSWORD: experiments
      POSTGRES_DB: experiments
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - experiments

networks:
  experiments:
    driver: bridge

volumes:
  postgres_data:
